language: node_js
node_js:
  - '0.10'
  - '0.8'
script: 'make coveralls'
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
